### ISSUE TITLE
Inference on GraspNet1Billion dataset 

### ISSUE THREAD

**Issue by elenacliu** [kmittle/Grasp-Detection-NBMOD#1]
Hello author,

I tried your test code on GraspNet1Billion dataset, but got the results. It may be wrong?

<img width="666" alt="image" src="https://github.com/kmittle/Grasp-Detection-NBMOD/assets/44845151/88d4481f-f27a-4d40-85e3-3f929869b3d5">

**Comment by elenacliu** [comment]
I find the reason. I should use the (300,400,3) size image to draw the box on.

**Comment by Andyyoung0507** [comment]
> I find the reason. I should use the (300,400,3) size image to draw the box on.
Why the image size should be (300,400,3), I use my own picture to generate the grasp, the results are also strange. Only one box but beyond the desired object. @elenacliu

**Comment by kmittle** [comment]
The size I used in my experiment was 416 x 416.&nbsp;You can modify the meshing method to detect images of any size.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月5日(星期五) 中午11:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [kmittle/Grasp-Detection-NBMOD] Inference on GraspNet1Billion dataset  (Issue #1)





  
I find the reason. I should use the (300,400,3) size image to draw the box on.
 Why the image size should be (300,400,3), I use my own picture to generate the grasp, the results are also strange. Only one box but beyond the desired object.

**Comment by Andyyoung0507** [comment]
> The size I used in my experiment was 416 x 416.&nbsp;You can modify the meshing method to detect images of any size.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年1月5日(星期五) 中午11:42 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [kmittle/Grasp-Detection-NBMOD] Inference on GraspNet1Billion dataset (Issue #1) I find the reason. I should use the (300,400,3) size image to draw the box on. Why the image size should be (300,400,3), I use my own picture to generate the grasp, the results are also strange. Only one box but beyond the desired object. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

Thank you. I am sorry about that I didn't find the meshing method in the code repository and the paper, I just modified the boxes value by scaling up the ratio between the input image size and 416, but the results seems not so well. What should I do to improve the performance of generated grasp? Thanks!
<img width="147" alt="1" src="https://github.com/kmittle/Grasp-Detection-NBMOD/assets/45235840/28bb39d9-a881-4263-a46c-b5770b6ade77">
