### ISSUE TITLE
关于RAGT-3-3训练参数的疑问

### ISSUE THREAD

**Issue by panlexin** [kmittle/Grasp-Detection-NBMOD#5]
作者你好，我想根据代码尝试复现RAGT-3-3模型。想请问在训练RAGT-3-3时进行了多少epoch？以及输入的label是代码中给出的txt文件格式吗。我根据readme中的方法对NBMOD的图片进行了预处理。但发现即使用RAGT-3-3作为预训练权重，训练过程依然有着很高的loss，训练后的效果也不佳。感觉像是训练RAGT-3-3时的数据预处理跟github代码中的不一样。

**Comment by kmittle** [comment]
30个epoch，这个问题前面的帖子我回复过了，建议你要认真看别人的问题，而不是反复问，另外，如果你觉得我的数据处理不合适，可以用你自己的

**Comment by kmittle** [comment]
30，前面回复过了，数据处理如果你觉得不好，可以用你自己的

**Comment by kmittle** [comment]
还有，我建议你换个方式问问题，不要说这种没朋友的话

**Comment by kmittle** [comment]
还有，我建议你换个方式问问题，如果你发现了代码什么问题，欢迎你提出来，我也非常感谢你能纠正我的错误，但请你不要说这种没朋友的话

**Comment by kmittle** [comment]
还有，我建议你换个方式问问题。如果你发现了代码什么问题，欢迎你提出来，我也非常感谢你能纠正我的错误。

**Comment by kmittle** [comment]
如果你发现了代码什么问题，欢迎你提出来，我也非常感谢你能纠正我的错误，但是我建议你换个方式问问题。

**Comment by NeverlanD0829** [comment]
> 作者你好，我想根据代码尝试复现RAGT-3-3模型。想请问在训练RAGT-3-3时进行了多少epoch？以及输入的label是代码中给出的txt文件格式吗。我根据readme中的方法对NBMOD的图片进行了预处理。但发现即使用RAGT-3-3作为预训练权重，训练过程依然有着很高的loss，训练后的效果也不佳。感觉像是训练RAGT-3-3时的数据预处理跟github代码中的不一样。

您好，请问有解决这个问题吗？我也在复现过程中遇到了类似的问题。谢谢
